{{- if not (.Capabilities.APIVersions.Has "route.openshift.io/v1") }}
  {{- $clearHost := "" -}}
  {{- if not (and (.Values.main.istio) (eq .Values.main.istio.enable true)) }}
    {{- if .Values.route.enabled }}
      {{- $clearHost = printf "%s.%s" .Release.Name .Values.global.k8shost }}
      {{- if .Values.route.host }}
        {{- $clearHost = .Values.route.host }}
      {{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Values.route.name | default .Release.Name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
      {{- if .Values.route.path }}
    nginx.ingress.kubernetes.io/rewrite-target: /
      {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  tls:
    - hosts:
        - {{ $clearHost | trim }}
  rules:
      - host: {{ $clearHost | trim }}
        http:
          paths:
              - path: {{ .Values.route.path | default "/" }}
                pathType: Prefix
                backend:
                  service:
                    name: {{ .Release.Name }}
                    port:
                      name: http-{{ .Values.main.port }}
    {{- end }}
  {{- end }}
{{- end }}