kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - name: http-{{ .Values.main.port }}
      protocol: TCP
      port: {{ .Values.main.port }}
      targetPort: {{ .Values.main.port }}
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
  sessionAffinity: None