apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dashboard-backend
  namespace: server-dashboard
  labels:
    app: server-dashboard-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-dashboard-backend
  template:
    metadata:
      labels:
        app: server-dashboard-backend
    spec:
      containers:
      - name: backend
        image: server-dashboard-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DB_URL
          value: "jdbc:postgresql://postgres-service:5432/server_dashboard"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: server-dashboard-backend
  namespace: server-dashboard
  labels:
    app: server-dashboard-backend
spec:
  selector:
    app: server-dashboard-backend
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP

