global:
  # Openshift namespace в который производится деплой
  namespace: ds1-genr01-onbc-onb-development
  # Репозиторий из которого загружаются образы
  registry: nexus-ci.corp.dev.vtb/onb-docker-snapshot