global:
  # Openshift namespace в который производится деплой
  namespace: ds1-genr01-onbc-onb-development
  # Репозиторий из которого загружаются образы
  registry: nexus-ci.corp.dev.vtb/onb-docker-snapshot/smeo
  # Код проекта для мониторинга

route:
  enabled: true
  name:

# Настройки основного приложения
main:
  # Количество реплик подов
  replicaCount: 1
  # Образ в репозитории
  image: ""
  # Тег образа
  tag: ""
  # Политика кеширования образов на нодах
  pullPolicy: Always
  # Порт, на котором принимает запросы приложение
  port: 8080
  # Ресурсы, выделяемые на под
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi
  # Имя Service Account'а (builder, default, deployer, deploy-sa, prometheus)
  serviceAccount: prometheus
  serviceAccountName: prometheus
  # Параметры проб для main
  Probe:
    enabled: true
    livenessProbe:
      exec:
        command: /app/version.sh
      timeoutSeconds: 20
      periodSeconds: 60
    readinessProbe:
      httpGet:
        path: /
        port: 8080
        scheme: HTTP
      timeoutSeconds: 20
      periodSeconds: 30
