global:
  # Openshift namespace в который производится деплой
  namespace: ds1-genr01-onbc-onb-development
  # Репозиторий из которого загружаются образы
  registry: nexus-ci.corp.dev.vtb/onb-docker-snapshot
  # Код проекта для мониторинга
  projectCode: SMEO
  # Стенд, используется для создания секретов с нужными сертификатами для конкретного стенда
  stand: dev

route:
  enabled: true
  name:

# Настройки основного приложения
main:
  # Количество реплик подов
  replicaCount: 1
  # Образ в репозитории
  image: ""
  # Тег образа
  tag: ""
  # Политика кеширования образов на нодах
  pullPolicy: Always
  # Порт, на котором принимает запросы приложение
  port: 8080
  # Ресурсы, выделяемые на под
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi
  # Параметры проб для main
  Probe:
    enabled: true
    livenessProbe:
      exec:
        command: /app/version.sh
      timeoutSeconds: 20
      periodSeconds: 120
    readinessProbe:
      exec:
        command: /app/version.sh
      timeoutSeconds: 20
      periodSeconds: 180