global:
  # Openshift namespace в который производится деплой
  namespace: rs1-genr01-onbc-onb-preprod
  # Репозиторий из которого загружаются образы
  registry: nexus-cd.region.vtb.ru/onb-docker-test-g

route:
  enabled: true
  name:

# Настройки основного приложения
main:
  # Количество реплик подов
  replicaCount: 1
  # Образ в репозитории
  image: ""
  # Тег образа
  tag: ""
  # Политика кеширования образов на нодах
  pullPolicy: Always
  # Порт, на котором принимает запросы приложение
  port: 8080
