global:
  # K8s namespace в который производится деплой
  namespace: pk5-cole01-dcos-dcos
  # Репозиторий из которого загружаются образы
  registry: pcss-prod.region.vtb.ru:5000/dcos-docker-prod_si
main:
  image: dcos/ms-dashbord